---
  sudo: required

  language: bash

  services: docker

  cache:
    timeout: 1000
    directories:
      - $TRAVIS_HOME/cache

  stages:
    - precache
    - test

  jobs:
    include:
      - stage: precache
        before_install:
          - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
          - chmod +x docker-compose
          - sudo mv docker-compose /usr/local/bin
          - mkdir -p $TRAVIS_HOME/cache
          - |
            for n in 10 20 30 40 50; do
              dd if=/dev/zero of=$TRAVIS_HOME/cache/$n.bin bs=1M count=$n;
              cp $TRAVIS_HOME/cache/$n.bin .;
              size=$n docker-compose build;
              docker save myapache:$n -o $TRAVIS_HOME/cache/$n.tar.gz;
            done
      - stage: test
        before_install:
          - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
          - chmod +x docker-compose
          - sudo mv docker-compose /usr/local/bin
        install:
          - docker load -i $TRAVIS_HOME/cache/10.tar.gz
        script:
          - ls -al $TRAVIS_HOME/cache/
          - size=10 docker-compose up -d
          - sleep 5
          - wget -O 10.bin "http://localhost:8080/10.bin"
          - test $(stat --printf="%s" "10.bin") -ge $((10 * 1024 * 1024))
          - docker-compose down
      - stage: test
        before_install:
          - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
          - chmod +x docker-compose
          - sudo mv docker-compose /usr/local/bin
        install:
          - docker load -i $TRAVIS_HOME/cache/20.tar.gz
        script:
          - ls -al $TRAVIS_HOME/cache/
          - size=20 docker-compose up -d
          - sleep 5
          - wget -O 20.bin "http://localhost:8080/20.bin"
          - test $(stat --printf="%s" "20.bin") -ge $((20 * 1024 * 1024))
      - stage: test
        before_install:
          - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
          - chmod +x docker-compose
          - sudo mv docker-compose /usr/local/bin
        install:
          - docker load -i $TRAVIS_HOME/cache/30.tar.gz
        script:
          - ls -al $TRAVIS_HOME/cache/
          - size=30 docker-compose up -d
          - sleep 5
          - wget -O 30.bin "http://localhost:8080/30.bin"
          - test $(stat --printf="%s" "30.bin") -ge $((30 * 1024 * 1024))
      - stage: test
        before_install:
          - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
          - chmod +x docker-compose
          - sudo mv docker-compose /usr/local/bin
        install:
          - docker load -i $TRAVIS_HOME/cache/40.tar.gz
        script:
          - ls -al $TRAVIS_HOME/cache/
          - size=40 docker-compose up -d
          - sleep 5
          - wget -O 40.bin "http://localhost:8080/40.bin"
          - test $(stat --printf="%s" "40.bin") -ge $((40 * 1024 * 1024))
      - stage: test
        before_install:
          - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
          - chmod +x docker-compose
          - sudo mv docker-compose /usr/local/bin
        install:
          - docker load -i $TRAVIS_HOME/cache/50.tar.gz
        script:
          - ls -al $TRAVIS_HOME/cache/
          - size=50 docker-compose up -d
          - sleep 5
          - wget -O 50.bin "http://localhost:8080/50.bin"
          - test $(stat --printf="%s" "50.bin") -ge $((50 * 1024 * 1024))
