---
  sudo: required

  language: bash

  services: docker

  env:
    global:
      - DOCKER_COMPOSE_VERSION=1.23.2

  cache:
    timeout: 1000
    directories:
      - $TRAVIS_HOME/cache

  _test: &_test
    stage: test
    before_install:
      - sudo cp $TRAVIS_HOME/cache/docker-compose /usr/local/bin
      - sudo chmod +x /usr/local/bin/docker-compose
    install:
      - docker load -i $TRAVIS_HOME/cache/$TRAVIS_JOB_NAME.tar.gz
    script:
      - ls -al $TRAVIS_HOME/cache/
      - size=$TRAVIS_JOB_NAME docker-compose up -d
      - sleep 5
      - wget -O $TRAVIS_JOB_NAME.bin "http://localhost:8080/${TRAVIS_JOB_NAME}.bin"
      - test $(stat --printf="%s" "${TRAVIS_JOB_NAME}.bin") -ge $(($TRAVIS_JOB_NAME * 1024 * 1024))

  stages:
    - precache
    - test

  jobs:
    include:
      - stage: precache
        before_install:
          - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
          - chmod +x docker-compose
          - sudo cp docker-compose $TRAVIS_HOME/cache/docker-compose
          - sudo mv docker-compose /usr/local/bin
          - mkdir -p $TRAVIS_HOME/cache
          - |
            for n in 10 20 30 40 50; do
              dd if=/dev/zero of=$TRAVIS_HOME/cache/$n.bin bs=1M count=$n;
              cp $TRAVIS_HOME/cache/$n.bin .;
              size=$n docker-compose build;
              docker save myapache:$n -o $TRAVIS_HOME/cache/$n.tar.gz;
            done
      - <<: *_test
        name: 5
      - <<: *_test
        name: 10
      - <<: *_test
        name: 20
      - <<: *_test
        name: 30
      - <<: *_test
        name: 40
      - <<: *_test
        name: 50
